### ISSUE TITLE
missing install howto and SQL base to import

### ISSUE THREAD

**Issue by Albirew** [tslocum/teechan#2]
Hi, I'm currently trying to install teechan.
What I've done so far is:
- extract teechan on web server
- create a SQL database named www
- copy settings.default.php to settings.php and customized it (TEE_SALT, TEE_PDODSN, TEE_PDOUSER and TEE_PDOPASS)

And... that's all I could figure by myself.

When trying to connect using shhichan's default login (admin5:default), I get a blank webpage and my error.log shows:
`PHP Notice:  Undefined index: teeaccname in /var/www/teechan/admin.php on line 83, referer: http://192.168.1.11/teechan/admin.php`

`PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'www.accounts' doesn't exist' in /var/www/teechan/include.php:117\nStack trace:\n#0 /var/www/teechan/include.php(117): PDO->prepare('SELECT * FROM a...')\n#1 /var/www/teechan/include.php(87): accountByUsername('admin5')\n#2 /var/www/teechan/admin.php(89): checkCredentials('admin5', 'default')\n#3 {main}\n  thrown in /var/www/teechan/include.php on line 117, referer: http://192.168.1.11/teechan/admin.php`

Where is the .sql file to import?

**Comment by tslocum** [comment]
Hey @Albirew, at the moment there isn't a SQL file to import.  I created this project and quickly lost interest as it needs a lot of work.  I wouldn't recommend using it as I haven't finished checking for vulnerabilities which may have been present in shiichan.  If you're interested in working on it, and submitting your changes back upstream, I'll gladly share a dump of what I have.

**Comment by ghost** [comment]
If you're still around, I would love a copy of that dump. Any changes I would make would be committed to my fork.

**Comment by Albirew** [comment]
closed due to old age

**Comment by tslocum** [comment]
```
-- Adminer 4.7.1 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';

CREATE DATABASE `teechan` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `teechan`;

CREATE TABLE `accounts` (
  `id` int(5) NOT NULL AUTO_INCREMENT,
  `username` varchar(75) NOT NULL,
  `password` varchar(255) NOT NULL,
  `loginkey` varchar(75) NOT NULL,
  `addedby` int(5) NOT NULL,
  `added` int(20) NOT NULL,
  `lastactive` int(20) NOT NULL DEFAULT 0,
  `level` int(4) NOT NULL,
  `capcode` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `bans` (
  `ip` varchar(46) NOT NULL,
  `pubreason` text NOT NULL,
  `privreason` text NOT NULL,
  `by` int(5) NOT NULL,
  `at` int(20) NOT NULL,
  `expires` int(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `mohel` (
  `mohel` varchar(75) NOT NULL,
  `by` int(5) NOT NULL,
  `at` int(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `posts` (
  `board` varchar(75) NOT NULL,
  `id` mediumint(7) NOT NULL AUTO_INCREMENT,
  `parent` mediumint(7) unsigned NOT NULL,
  `threadid` int(20) NOT NULL DEFAULT 0,
  `timestamp` int(20) NOT NULL,
  `bumped` int(20) NOT NULL,
  `ip` varchar(15) NOT NULL,
  `name` varchar(75) NOT NULL,
  `tripcode` varchar(10) NOT NULL,
  `email` varchar(75) NOT NULL,
  `nameblock` varchar(255) NOT NULL,
  `subject` varchar(75) NOT NULL,
  `message` text NOT NULL,
  PRIMARY KEY (`board`,`id`),
  KEY `parent` (`parent`),
  KEY `bumped` (`bumped`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


-- 2019-08-12 17:42:48
```
